// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Primary content in *ValidateOtp → Default → Primary*
 */
export interface ValidateOtpSliceDefaultPrimary {
  /**
   * title field in *ValidateOtp → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: validate_otp.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Default variation for ValidateOtp Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ValidateOtpSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ValidateOtpSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ValidateOtp*
 */
type ValidateOtpSliceVariation = ValidateOtpSliceDefault;

/**
 * ValidateOtp Shared Slice
 *
 * - **API ID**: `validate_otp`
 * - **Description**: ValidateOtp
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ValidateOtpSlice = prismic.SharedSlice<
  "validate_otp",
  ValidateOtpSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client;
  }

  namespace Content {
    export type {
      ValidateOtpSlice,
      ValidateOtpSliceDefaultPrimary,
      ValidateOtpSliceVariation,
      ValidateOtpSliceDefault,
    };
  }
}
